### ISSUE TITLE
Known Issue - Deluge locale

### ISSUE THREAD

**Issue by Kabe0** [Kabe0/deluge-windscribe#10]
Upgrading to Ubuntu 20.04 which reduces it's size quit significantly, however the deluge service throws a locale error when it runs.

```
Unable to initialize gettext/locale!
'ngettext'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/i18n/util.py", line 118, in setup_translation
    builtins.__dict__['_n'] = builtins.__dict__['ngettext']
KeyError: 'ngettext'
```

This is not a real error (apparently) deluge team just has to get around to fixing it. It does not effect the service itself but is quite annoying

**Comment by ronioncloud** [comment]
> Upgrading to Ubuntu 20.04 which reduces it's size quit significantly, however the deluge service throws a locale error when it runs.
> 
> ```
> Unable to initialize gettext/locale!
> 'ngettext'
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/deluge/i18n/util.py", line 118, in setup_translation
>     builtins.__dict__['_n'] = builtins.__dict__['ngettext']
> KeyError: 'ngettext'
> ```
> 
> This is not a real error (apparently) deluge team just has to get around to fixing it. It does not effect the service itself but is quite annoying
> 
> https://forum.deluge-torrent.org/viewtopic.php?t=55673

same issue here

**Comment by louis6999** [comment]
Hi,

I have the same issue. I try to fixe with deluge forum topic but i can't resolve my problem. 

Initializing Container,
Using VPN_USERNAME and VPN_PASSWORD to login.,
Starting windscribe ... OK,
Settings location to best,
Initializing Deluge,
Configuring firewall settings,
Setting UID to 1000,
usermod: no changes,
Setting GID to 1000,
Deluged Init,
Unable to initialize gettext/locale!,
'ngettext',
Traceback (most recent call last):,
  File "/usr/lib/python3/dist-packages/deluge/i18n/util.py", line 118, in setup_translation,
    builtins.__dict__['_n'] = builtins.__dict__['ngettext'],
KeyError: 'ngettext',
STARTING TINYPROXY,
Found config file /etc/tinyproxy/tinyproxy.conf, updating settings.,
Setting tinyproxy port to 8888,
tinyproxy is on the PATH, run it,
Tinyproxy startup script complete.,

**Comment by Kabe0** [comment]
The deluge locale error itself does not in anyway actually effect the performance or function of deluge. It's something the deluge team will have to address in the future.
