### ISSUE TITLE
Observer Error in logs repeatedly

### ISSUE THREAD

**Issue by cheekoo** [Kabe0/deluge-windscribe#24]
Thanks for creating this awesome image! I see this log over and over in console. Am I setting it up wrong? If you need any further information, I am happy to provide that. 

Temporarily disabling observer LegacyLogObserverWrapper(<bound method TwistedLoggingObserver.emit of <deluge.log.TwistedLoggingObserver object at 0x7fde702ade50>>) due to exception: [Failure instance: Traceback: <class 'TypeError'>: findCaller() takes from 1 to 2 positional arguments but 3 were given
/usr/lib/python3/dist-packages/twisted/python/failure.py:766:_safeReprVars
/usr/lib/python3/dist-packages/twisted/internet/defer.py:962:__del__
/usr/lib/python3/dist-packages/twisted/logger/_logger.py:190:failure
/usr/lib/python3/dist-packages/twisted/logger/_logger.py:144:emit
--- <exception caught here> ---
/usr/lib/python3/dist-packages/twisted/logger/_observer.py:131:__call__
/usr/lib/python3/dist-packages/twisted/logger/_legacy.py:93:__call__
/usr/lib/python3/dist-packages/deluge/log.py:204:emit
/usr/lib/python3.9/logging/__init__.py:1489:critical
/usr/lib/python3.9/logging/__init__.py:1573:_log
]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 766, in _safeReprVars
    return [(name, reflect.safe_repr(obj)) for (name, obj) in varsDictItems]
  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 962, in __del__
    log.failure(format,
  File "/usr/lib/python3/dist-packages/twisted/logger/_logger.py", line 190, in failure
    self.emit(level, format, log_failure=failure, **kwargs)
  File "/usr/lib/python3/dist-packages/twisted/logger/_logger.py", line 144, in emit
    self.observer(event)
--- <exception caught here> ---
  File "/usr/lib/python3/dist-packages/twisted/logger/_observer.py", line 131, in __call__
    observer(event)
  File "/usr/lib/python3/dist-packages/twisted/logger/_legacy.py", line 93, in __call__
    self.legacyObserver(event)
  File "/usr/lib/python3/dist-packages/deluge/log.py", line 204, in emit
    getattr(LoggingLoggerClass, event_dict['log_level'].name)(
  File "/usr/lib/python3.9/logging/__init__.py", line 1489, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/usr/lib/python3.9/logging/__init__.py", line 1573, in _log
    fn, lno, func, sinfo = self.findCaller(stack_info, stacklevel)
builtins.TypeError: findCaller() takes from 1 to 2 positional arguments but 3 were given

**Comment by Kabe0** [comment]
What distro are you using? I have not seen that error reported from anyone yet. If this is coming from Deluge, I don't really have any control over the errors it want's to throw.

**Comment by cheekoo** [comment]
I am using alpine-linux. it could be from deluge, I will try to look for a longer stack trace. 

How can we identify if its coming from deluge or VPN?

**Comment by cheekoo** [comment]
I looked at error stack trace again - and we do have "deluge.log.TwistedLoggingObserver object" in it. So probably deluge related.

**Comment by Kabe0** [comment]
Sigh, yea there are a few of those errors now that python has been updated. I am not sure when their next release is going to be.
