### ISSUE TITLE
"Please login to use Windscribe"

### ISSUE THREAD

**Issue by pearlythepirate** [Kabe0/deluge-windscribe#4]
I've tried setting my Windscribe username and password in the environment variables and the /config/auth.conf file but both methods produce an error. Please let me know if you need anymore info.

Using Docker Linux, bridge network

```
Starting windscribe ... OK,
Initializing Container,
Traceback (most recent call last):,
  File "/usr/bin/init.py", line 50, in <module>,
  File "/usr/local/lib/python3.6/dist-packages/pexpect/spawnbase.py", line 344, in expect,
    cond = child.expect(['Please login to use Windscribe', 'Service communication error', pexpect.EOF], timeout=50),
    timeout, searchwindowsize, async_),
  File "/usr/local/lib/python3.6/dist-packages/pexpect/spawnbase.py", line 372, in expect_list,
  File "/usr/local/lib/python3.6/dist-packages/pexpect/expect.py", line 181, in expect_loop,
    return exp.expect_loop(timeout),
    return self.timeout(e),
  File "/usr/local/lib/python3.6/dist-packages/pexpect/expect.py", line 144, in timeout,
    raise exc,
pexpect.exceptions.TIMEOUT: Timeout exceeded.,
<pexpect.pty_spawn.spawn object at 0x7f3c2ed4c550>,
command: /usr/bin/windscribe,
args: ['/usr/bin/windscribe', 'firewall', 'on'],
buffer (last 100 chars): b'',
before (last 100 chars): '',
after: <class 'pexpect.exceptions.TIMEOUT'>,
match_index: None,
exitstatus: None,
match: None,
flag_eof: False,
child_fd: 5,
pid: 170,
closed: False,
timeout: 30,
delimiter: <class 'pexpect.exceptions.EOF'>,
logfile: None,
logfile_read: None,
logfile_send: None,
maxread: 2000,
ignorecase: False,
searchwindowsize: None,
delaybeforesend: 0.05,
delayafterclose: 0.1,
delayafterterminate: 0.1,
    0: re.compile(b'Please login to use Windscribe'),
    1: re.compile(b'Service communication error'),
    2: EOF,
searcher: searcher_re:
```

**Comment by Kabe0** [comment]
I have seen the message _Service communication error_ usually when there is no internet connection. Can you confirm that the docker container can connect to the internet?
You can launch the container using the following command

```
docker run \
 -v $PWD/config:/config \
 -v $PWD/downloads:/downloads \
 -p 8112:8112 \
 --cap-add=NET_ADMIN \
 --device /dev/net/tun:/dev/net/tun \
 --name deluge-windscribe-test \
 -it \
 kabe0/deluge-windscribe /bin/bash
```

Run apt-get update, if this fails to run, your docker container does not have any internet. Let me know what OS you are using and are you using ethernet or wifi?

**Comment by pearlythepirate** [comment]
It was a DNS issue as you mentioned. I set the DNS address manually via the Portainer config for the container and it connected no issues. Thanks for your help!
